---
  - name: "update apt packages."
    apt:
      update_cache: yes

  - name: "upgrade packages"
    apt:
      upgrade: yes

  - name: remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: install node
    shell: |
      curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash - && sudo apt-get install -y nodejs

  - name: "Install zip utility."
    apt:
      name: [ "zip", "unzip" ]
      state: latest
      update_cache: yes

  - name: "install pm2"
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: Copy files
    become: true
    copy:
      src: /root/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz

  - name: Unarchive
    become: true
    shell : |
        cd /home/ubuntu/
        tar xvzf artifact.tar.gz -C .
        
  - name: "run server"
    become: true
    shell : |
        cd /home/ubuntu/
        npm install
        pm2 stop default
        sudo pm2 start npm backend -- start
    environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"