version: 2.1

commands:
  dependencies:
    steps:
      - run:
          name: Installing necessary packages
          command: |
            sudo apt update
            sudo apt install -y tar gzip curl software-properties-common
      - run:
          name: Installing ansible
          command: |
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible

  ensure-backend-env-exists:
    description: Add .env file due to connection problems
    steps:
      - run:
          name: Create backend .env
          command: |
            echo -e "NODE_ENV=local\nVERSION=1\nTYPEORM_CONNECTION=${TYPEORM_CONNECTION}\nTYPEORM_MIGRATIONS_DIR=${TYPEORM_MIGRATIONS_DIR}\nTYPEORM_ENTITIES=${TYPEORM_ENTITIES}\nTYPEORM_MIGRATIONS=${TYPEORM_MIGRATIONS}\nTYPEORM_HOST=${TYPEORM_HOST}\nTYPEORM_PORT=${TYPEORM_PORT}\nTYPEORM_USERNAME=${TYPEORM_USERNAME}\nTYPEORM_PASSWORD=${TYPEORM_PASSWORD}\nTYPEORM_DATABASE=${TYPEORM_DATABASE}" >> backend/.env    
      

  destroy_environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      workflow_id:
        type: "string"
        default: ${CIRCLE_WORKFLOW_ID:0:7}
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws s3 rm s3://udapeople-<< parameters.workflow_id >> --recursive
            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_id >>
            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_id >>
          # aws cloudformation delete-stack --stack-name postgressDb

  revert_migrations:
    description: Revert the last migration if successfully run in the current workflow.
    parameters:
      workflow_id:
        type: string
        default: ${CIRCLE_WORKFLOW_ID:0:7}
    steps:
      - run:
          name: Revert migrations
          when: on_fail
          command: |
            SUCCESS=$(curl --insecure  https://kvdb.io/32huAaHdSpQL9ECfBWzFCL/migration_<< parameters.workflow_id >>)

            if (( $SUCCESS == 1 ));
            then
             cd ~/project/backend
             npm install
             npm run migrations:revert
            else
                echo "No migrations to revert"
            fi

jobs:
  build_frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            # Your code here
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build_backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            # Your code here
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test_frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-test]
      - run:
          name: Test frontend
          command: |
            cd frontend
            npm install
            npm run test

  test_backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-test]
      - run:
          name: Test build-backend
          command: |
            cd backend
            npm install
            npm run test

  scan_frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      # - restore_cache:
      #     keys: [frontend-scan]
      - run:
          name: Scan frontend
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
  

  scan_backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      # - restore_cache:
      #     keys: [backend-scan]
      - run:
          name: scan backend
          command: |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force

  deploy_infrastructure:
    docker:
      - image: cimg/aws:2023.01
    steps:
      - checkout
      - dependencies

      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
              --region us-east-1 \
              --tags project=udapeople
      - run:
          name: Ensure front-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
              --region us-east-1 \
              --tags project=udapeople
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> .circleci/ansible/inventory.txt
            cat .circleci/ansible/inventory.txt
      
      - ensure-backend-env-exists

      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt
      - destroy_environment:
          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["df:83:e0:88:9c:f0:43:f7:cb:da:a9:0c:79:5c:7d:9e"]
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies  
          command: |
            apk add curl
            apk add --upgrade bash
            apk add --update ansible
            apk add openssh-client
            pip3 install awscli
      - run:
          name: Configure server
          command: |
            cat ~/project/.circleci/ansible/inventory.txt
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook -i ~/project/.circleci/ansible/inventory.txt ~/project/.circleci/ansible/configure-server.yml
      
      - destroy_environment



  run_migrations:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - attach_workspace:
          at: ~/
      - run:
          name: Run migrations
          command: |
            cd backend
            npm install
            npm run migrations >> migrations_dump.txt
            cat migrations_dump.txt
      - run:
          name: Send migration results to kvdb.io
          command: |
            cd backend
            if grep -q "has been executed successfully." migrations_dump.txt
            then
                  curl https://kvdb.io/32huAaHdSpQL9ECfBWzFCL/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
            else
              echo "Not executed successfully"
            fi

  deploy_frontend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update tar gzip ansible nodejs npm curl
            pip install awscli
      - run:
          name: Get backend url
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)  
            export API_URL="http://${BACKEND_IP}:3030"
            echo "API_URL = ${API_URL}"
            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
            cat frontend/.env

      - run:
          name: Deploy frontend objects
          command: |
            cd frontend
            npm install
            npm run build
            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive

      - destroy_environment
      - revert_migrations

  deploy_backend:
    docker:
      - image: python:3.7-alpine3.11
      # - image: cimg/python:3.7-node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["e8:8c:9d:22:3d:ac:9d:a4:a0:81:e7:cd:14:f8:06:48"]
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Install dependencies
          command: |
            apk add --update tar gzip ansible nodejs npm curl openssh-client
            pip install awscli
        
      - run:
          name: Deploy backend
          command: |
            cd backend
            npm install
            npm run build
            cd ..
            tar -C backend -czvf artifact.tar.gz .
            cd .circleci/ansible
            ansible-playbook -i inventory.txt deploy-backend.yml
          

      - destroy_environment
      - revert_migrations

 
  

      
      
      # - revert_migrations
  test_revert_migrations:
    docker:
      # - image: cimg/aws:2023.01
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Revert migrations
          command: |
            cd ~/project/backend
            npm install
            npm run migrations:revert
  
  smoke_test:
    docker:
      # - image: cimg/aws:2023.01
      # - image: python:3.7-alpine3.11
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Backend smoke test
          command: |
            export BACKEND_IP_ADD=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
            export API_URL="http://${BACKEND_IP_ADD}:3030"
            echo "${API_URL}"
            if curl "${API_URL}/api/status" | grep "ok"
            then
              exit 0
            else
              exit 1
            fi
      - run:
          name: Frontend smoke test
          command: |
            if curl -s  "http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com" | grep "Welcome"
            then
               exit 1
            else
               exit 1
            fi

      - destroy_environment
      - revert_migrations
  
  cloudfront_update:
    docker:
      - image: cimg/aws:2023.01
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            # your code here
      - run:
          name: Save Old Worldflow Id
          command: |
              export OldWorkflowID=$(aws cloudformation \
              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
              --no-paginate --output text)

              echo OldWokflowID: "$OldWorkflowID"
              curl https://kvdb.io/32huAaHdSpQL9ECfBWzFCL/old_workflow_id -d "${OldWorkflowID}"


              aws cloudformation deploy \
              --template-file .circleci/files/cloudfront.yml \
              --stack-name  InitialStack \
              --region us-east-1 \
              --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project=udapeople

              echo OldWorkflowId: ${OldWorkflowID}
              echo Current WorkflowId: ${CIRCLE_WORKFLOW_ID:0:7}
      # - run :
      #     name: Cloudfront update
      #     command: |
      #       aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"

      - destroy_environment
      - revert_migrations

  cleanup:
    docker:
      - image: cimg/aws:2023.01
    steps:
      - checkout
      - attach_workspace:
            at: ~/
      - run:
          name: Remove old stacks and files
          command: |
              
              # Fetch the Old workflow ID
              export OldWorkflowID=$(curl --insecure https://kvdb.io/32huAaHdSpQL9ECfBWzFCL/old_workflow_id)
              echo "Old Wokflow ID: $OldWorkflowID"
              echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"

              # Fetch the stack names          
              export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
                        --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
              echo Stack names: "${STACKS[@]}"  

              
              if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
              then
                    echo "-------------Initiating Cleanup-------------------"
                    
                    aws s3 rm "s3://${OldWorkflowID}" --recursive
                    aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
                    aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"

                    echo "-------------Cleanup Completed-------------------"
              else
                    echo "--------------Cannot Cleanup---------------------"
              fi


      - destroy_environment
      - revert_migrations

workflows:
  default:
    jobs:
      # - test_revert_migrations
      - build_backend
      - build_frontend
      # - test_backend:
      #     requires:
      #       - build_backend
      # - test_frontend:
      #     requires:
      #       - build_frontend
      # - scan_backend:
      #     requires:
      #       - build_backend
      # - scan_frontend:
      #     requires:
      #       - build_frontend
      - deploy_infrastructure
          # requires:
          #   - test_frontend
          #   - test_backend
          #   - scan_backend
          #   - scan_frontend
      - configure_infrastructure:
          requires:
            - deploy_infrastructure
      - run_migrations:
          requires:
            - configure_infrastructure
      - deploy_frontend:
          requires:
            - run_migrations
      - deploy_backend:
          requires:
            - run_migrations
      - smoke_test:
          requires:
            - deploy_frontend
            - deploy_backend
      - cloudfront_update:
          requires:
            - smoke_test
      - cleanup:
          requires:
            - cloudfront_update
          

# trigger